//
// Created by Wout Briels on 29/11/2018.
//

#ifndef GBA_SPRITE_ENGINE_PROJECT_STARTSCENE_H
#define GBA_SPRITE_ENGINE_PROJECT_STARTSCENE_H


class StartScene {

};


#endif //GBA_SPRITE_ENGINE_PROJECT_STARTSCENE_H
