//
// Created by Florian on 6/01/2019.
//

#ifndef GBA_SPRITE_ENGINE_PROJECT_SPRITES_PALETTE_H
#define GBA_SPRITE_ENGINE_PROJECT_SPRITES_PALETTE_H

#endif //GBA_SPRITE_ENGINE_PROJECT_SPRITES_PALETTE_H

