//
// Created by tiele on 9/08/2019.
//

#ifndef GBA_SPRITE_ENGINE_PROJECT_PROFILE_SCENE_H
#define GBA_SPRITE_ENGINE_PROJECT_PROFILE_SCENE_H


class ProfileScene {

};


#endif //GBA_SPRITE_ENGINE_PROJECT_PROFILE_SCENE_H
