//
// Created by lloyd on 28-Dec-18.
//

#ifndef GBA_SPRITE_ENGINE_PROJECT_DIRECTION_H
#define GBA_SPRITE_ENGINE_PROJECT_DIRECTION_H

enum class Direction {
    UP,DOWN,LEFT,RIGHT
};

#endif //GBA_SPRITE_ENGINE_PROJECT_DIRECTION_H
